FROM debian:bullseye
RUN apt-get update && apt install -y nginx
RUN apt install curl -y
RUN apt install vim -y
RUN mkdir -p /etc/nginx/ssl
RUN apt-get -y install openssl
RUN openssl req -x509 -nodes -out /etc/nginx/ssl/inception.crt -keyout /etc/nginx/ssl/inception.key -subj "/C=FR/ST=IDF/L=PARIS/0=42/OU=42/CN=tpotilli.42.fr/UID=tpotilli"

RUN mkdir -p /var/run/nginx

COPY ./conf/default.conf /etc/nginx/conf.d/default.conf
RUN chmod 755 /var/www/html
RUN chown -R www-data:www-data /var/www/html

RUN mkdir -p /var/www/wordpress && \
    chmod 755 /var/www/wordpress && \
    chown -R www-data:www-data /var/www/wordpress

EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]