FROM debian:bullseye
RUN apt-get update && apt install -y nginx
RUN apt install curl -y
RUN apt install vim -y
RUN mkdir -p /etc/nginx/ssl
RUN apt-get -y install openssl
RUN openssl req -x509 -nodes -out /etc/nginx/ssl/inception.crt -keyout /etc/nginx/ssl/inception.key -subj "/C=FR/ST=IDF/L=PARIS/0=42/OU=42/CN=tpotilli.42.fr/UID=tpotilli"

RUN mkdir -p /var/run/nginx

COPY conf/nginx.conf /etc/nginx/nginx.conf
RUN chmod 755 /var/www/html
RUN chown -R www-data:www-data /var/www/html

CMD ["nginx", "-g", "daemon off;"]
# refuser l'acces si autre port que 443
# modif le serv_name